version: "3"
services:
  traefik:
    image: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  swagger:
    image: holopanel/swagger
    build:
      context: .
      dockerfile: swagger/Dockerfile
    ports:
      - "8082:8080"
    labels:
      - traefik.http.routers.swagger.rule=Host(`swagger.localhost`)
      - traefik.http.services.swagger.loadbalancer.server.port=8080
  api:
    image: holopanel/api
    build:
      context: .
      dockerfile: cmd/Dockerfile
    ports:
      - "8081:8081"
    labels:
      - traefik.http.routers.api.rule=Host(`localhost`) && PathPrefix(`/api`)
      - traefik.http.middlewares.api-stripprefix.stripprefix.prefixes=/api
      - traefik.http.middlewares.api-cors.headers.accesscontrolalloworiginlist=*
      - traefik.http.routers.api.middlewares=api-stripprefix@docker,api-cors@docker
  ui:
    image: holopanel/ui
    build:
      context: .
      dockerfile: ui/Dockerfile
    ports:
      - "8083:80"
    labels:
      - traefik.http.routers.ui.rule=Host(`localhost`)
